/*
 * Lightsaber - Lightweight Transactions Processing Engine
 * This is a money transfer support API.  You can find out more about it on the project  at [https://github.com/amaksakov/lightweight_transactions](https://github.com/amaksakov/lightweight_transactions)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: amaksakov@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amaksakov.lightsaber.api;

import com.amaksakov.lightsaber.ApiException;
import com.amaksakov.lightsaber.api.client.AccountsApi;
import com.amaksakov.lightsaber.model.AccountId;
import com.amaksakov.lightsaber.model.AccountRequest;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for AccountsApi
 */
@Ignore
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Creates new account
     *
     * Creates new account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountTest() throws ApiException {
        AccountRequest body = null;
        AccountId response = api.createAccount(body);

        // TODO: test validations
    }
    
}
