/*
 * Lightsaber - Lightweight Transactions Processing Engine
 * This is a money transfer support API.  You can find out more about it on the project  at [https://github.com/amaksakov/lightweight_transactions](https://github.com/amaksakov/lightweight_transactions)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: amaksakov@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amaksakov.lightsaber.api;

import com.amaksakov.lightsaber.ApiException;
import com.amaksakov.lightsaber.api.client.TransactionsApi;
import com.amaksakov.lightsaber.model.AccountId;
import com.amaksakov.lightsaber.model.ChargeCommand;
import com.amaksakov.lightsaber.model.TransferCommand;
import com.amaksakov.lightsaber.model.TransferResult;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for TransactionsApi
 */
@Ignore
public class TransactionsApiTest {

    private final TransactionsApi api = new TransactionsApi();

    
    /**
     * Transfers money from/to account from external sources, like cash at ATM or counter
     *
     * Charges account/ withdraws money from account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountChargeTest() throws ApiException {
        ChargeCommand body = null;
        TransferResult response = api.accountCharge(body);

        // TODO: test validations
    }
    
    /**
     * Gets the account information, including current balance
     *
     * Gets the account information, including current balance
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountBalanceTest() throws ApiException {
        AccountId body = null;
        api.getAccountBalance(body);

        // TODO: test validations
    }
    
    /**
     * Transfers money from one account to another
     *
     * Transfers money from one account to another
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void moneyTransferTest() throws ApiException {
        TransferCommand body = null;
        TransferResult response = api.moneyTransfer(body);

        // TODO: test validations
    }
    
}
