/*
 * Lightsaber - Lightweight Transactions Processing Engine
 * This is a money transfer support API.  You can find out more about it on the project  at [https://github.com/amaksakov/lightweight_transactions](https://github.com/amaksakov/lightweight_transactions)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: amaksakov@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amaksakov.lightsaber.model;

import java.util.Objects;
import java.util.Arrays;
import com.amaksakov.lightsaber.model.AccountBalance;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TransferResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-26T12:26:01.127+01:00")
public class TransferResult {
  @SerializedName("newBalance")
  private AccountBalance newBalance = null;

  @SerializedName("transactionId")
  private String transactionId = null;

  public TransferResult newBalance(AccountBalance newBalance) {
    this.newBalance = newBalance;
    return this;
  }

   /**
   * Get newBalance
   * @return newBalance
  **/
  @ApiModelProperty(value = "")
  public AccountBalance getNewBalance() {
    return newBalance;
  }

  public void setNewBalance(AccountBalance newBalance) {
    this.newBalance = newBalance;
  }

  public TransferResult transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Transaction ID for tracking purposes
   * @return transactionId
  **/
  @ApiModelProperty(value = "Transaction ID for tracking purposes")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferResult transferResult = (TransferResult) o;
    return Objects.equals(this.newBalance, transferResult.newBalance) &&
        Objects.equals(this.transactionId, transferResult.transactionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newBalance, transactionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferResult {\n");
    
    sb.append("    newBalance: ").append(toIndentedString(newBalance)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

