/*
 * Lightsaber - Lightweight Transactions Processing Engine
 * This is a money transfer support API.  You can find out more about it on the project  at [https://github.com/amaksakov/lightweight_transactions](https://github.com/amaksakov/lightweight_transactions)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: amaksakov@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amaksakov.lightsaber.model;

import java.util.Objects;
import java.util.Arrays;
import com.amaksakov.lightsaber.model.AccountId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TransferCommand
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-26T12:26:01.127+01:00")
public class TransferCommand {
  @SerializedName("from")
  private AccountId from = null;

  @SerializedName("to")
  private AccountId to = null;

  @SerializedName("amount")
  private Long amount = null;

  public TransferCommand from(AccountId from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @ApiModelProperty(value = "")
  public AccountId getFrom() {
    return from;
  }

  public void setFrom(AccountId from) {
    this.from = from;
  }

  public TransferCommand to(AccountId to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @ApiModelProperty(value = "")
  public AccountId getTo() {
    return to;
  }

  public void setTo(AccountId to) {
    this.to = to;
  }

  public TransferCommand amount(Long amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Charge/withdraw amount in cents
   * @return amount
  **/
  @ApiModelProperty(value = "Charge/withdraw amount in cents")
  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferCommand transferCommand = (TransferCommand) o;
    return Objects.equals(this.from, transferCommand.from) &&
        Objects.equals(this.to, transferCommand.to) &&
        Objects.equals(this.amount, transferCommand.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferCommand {\n");
    
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

